### ISSUE TITLE
ipaddress.AddressValueError on RHEL 7.6

### ISSUE THREAD

**Issue by CNMan** [ipipdotnet/ipdb-python#2]
```
python-ipaddress.noarch             1.0.16-2.el7     @anaconda/7.5
```

```python
$ python
Python 2.7.5 (default, Sep 12 2018, 05:31:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ipdb
>>> db = ipdb.City("17monipdb.ipdb")
>>> print(db.is_ipv4(), db.is_ipv6())
(True, False)
>>> print(db.languages())
[u'CN']
>>> print(db.fields())
[u'country_name', u'region_name', u'city_name', u'owner_domain', u'isp_domain', u'latitude', u'longitude', u'timezone', u'utc_offset', u'china_admin_code', u'idd_code', u'country_code', u'continent_code']
>>> print(db.build_time())
1542805875
>>> print(db.find("1.1.1.1", "CN"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ipdb/city.py", line 56, in find
    return self.db.find(addr, language)
  File "/usr/lib/python2.7/site-packages/ipdb/database.py", line 112, in find
    ipv = ipaddress.ip_address(addr)
  File "/usr/lib/python2.7/site-packages/ipaddress.py", line 163, in ip_address
    ' a unicode object?' % address)
ipaddress.AddressValueError: '1.1.1.1' does not appear to be an IPv4 or IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?
>>> print(db.find_map("8.8.8.8", "CN"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ipdb/city.py", line 59, in find_map
    return self.db.find_map(addr, language)
  File "/usr/lib/python2.7/site-packages/ipdb/database.py", line 136, in find_map
    loc = self.find(addr, language)
  File "/usr/lib/python2.7/site-packages/ipdb/database.py", line 112, in find
    ipv = ipaddress.ip_address(addr)
  File "/usr/lib/python2.7/site-packages/ipaddress.py", line 163, in ip_address
    ' a unicode object?' % address)
ipaddress.AddressValueError: '8.8.8.8' does not appear to be an IPv4 or IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?
>>> print(db.find_info("118.28.1.1", "CN").country_name) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ipdb/city.py", line 62, in find_info
    m = self.db.find_map(addr, language)
  File "/usr/lib/python2.7/site-packages/ipdb/database.py", line 136, in find_map
    loc = self.find(addr, language)
  File "/usr/lib/python2.7/site-packages/ipdb/database.py", line 112, in find
    ipv = ipaddress.ip_address(addr)
  File "/usr/lib/python2.7/site-packages/ipaddress.py", line 163, in ip_address
    ' a unicode object?' % address)
ipaddress.AddressValueError: '118.28.1.1' does not appear to be an IPv4 or IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?
>>> exit()
```

**Comment by ilsanbao** [comment]
db.find(u"1.1.1.1", "CN")

**Comment by ilsanbao** [comment]
@CNMan
